/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_litrik_eclipse_xps_core_LEDs */

#ifndef _Included_com_litrik_eclipse_xps_core_LEDs
#define _Included_com_litrik_eclipse_xps_core_LEDs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_litrik_eclipse_xps_core_LEDs
 * Method:    setXpsColors
 * Signature: (CCCCC)I
 */
JNIEXPORT jint JNICALL Java_com_litrik_eclipse_xps_core_LEDs_setXpsColors
  (JNIEnv *, jclass, jchar, jchar, jchar, jchar, jchar);

#ifdef __cplusplus
}
#endif
#endif
